# Generated by Django 4.0.1 on 2022-01-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualHandlingCourseOutlineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The text that appears for the item.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ManualHandlingSummaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The text that appears for the item.', max_length=100)),
                ('icon_name', models.CharField(help_text='The code for the Font Awesome icon. See https://fontawesome.com/v5/cheatsheet. Example: address-book', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the site. Appears at the top of the browser in the tab and also appears in the copyright at the bottom', max_length=200)),
                ('nav_courses', models.CharField(help_text='Text for nav item which brings the user to the courses section.', max_length=20)),
                ('nav_contact', models.CharField(help_text='Text for nav item which brings the user to the contact section.', max_length=20)),
                ('hero_header', models.CharField(help_text='Big header that appears on the hero section.', max_length=200)),
                ('hero_description', models.TextField(help_text='Paragraph that appears under the hero header.')),
                ('hero_button_label', models.CharField(help_text='Text that appears inside the button on the hero page.', max_length=50)),
                ('about_column_one_header', models.CharField(help_text='Header for first column in about section', max_length=200)),
                ('about_column_one_description', models.TextField(help_text='Paragraph for first column in about section')),
                ('about_column_two_header', models.CharField(help_text='Header for second column in about section', max_length=200)),
                ('about_column_two_description', models.TextField(help_text='Paragraph for second column in about section')),
                ('about_column_three_header', models.CharField(help_text='Header for third column in about section', max_length=200)),
                ('about_column_three_description', models.TextField(help_text='Paragraph for third column in about section')),
                ('courses_header', models.CharField(help_text='Header for courses section', max_length=200)),
                ('courses_description', models.TextField(help_text='Paragraph that appears under header in courses section')),
                ('courses_manual_handling_header', models.CharField(help_text='Header for manual handing sub-section in courses section', max_length=200)),
                ('courses_manual_handling_description', models.TextField(help_text='Paragraph under manual handing header in courses section')),
                ('courses_other_courses_header', models.CharField(help_text='Header for other courses sub-section in courses section', max_length=200)),
                ('courses_other_courses_description', models.TextField(help_text='Paragraph under other courses header in courses section')),
                ('reviews_header', models.CharField(help_text='Header that appears on the reviews section.', max_length=200)),
                ('reviews_column_one_description', models.TextField(help_text='Paragraph for first column in reviews section')),
                ('reviews_column_one_author', models.CharField(help_text='Author for first column in reviews section', max_length=200)),
                ('reviews_column_two_description', models.TextField(help_text='Paragraph for second column in reviews section')),
                ('reviews_column_two_author', models.CharField(help_text='Author for second column in reviews section', max_length=200)),
                ('reviews_column_three_description', models.TextField(help_text='Paragraph for third column in reviews section')),
                ('reviews_column_three_author', models.CharField(help_text='Author for third column in reviews section', max_length=200)),
                ('contact_header', models.CharField(help_text='Header that appears on the contact section.', max_length=200)),
                ('contact_description', models.TextField(help_text='Paragraph that appears under the contact header.')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('linkedin', models.URLField(blank=True, max_length=128)),
                ('instagram', models.URLField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='OtherCoursesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The text that appears for the item.', max_length=100)),
            ],
        ),
    ]
