# Generated by Django 4.0.1 on 2022-01-11 15:06

from django.db import migrations
from django.db import transaction


def create_initial_data(apps, schema_editor):
    SiteSettings = apps.get_model('app', 'SiteSettings')
    ManualHandlingSummaryItem = apps.get_model('app', 'ManualHandlingSummaryItem')
    ManualHandlingCourseOutlineItem = apps.get_model('app', 'ManualHandlingCourseOutlineItem')
    OtherCoursesItem = apps.get_model('app', 'OtherCoursesItem')

    site_settings = SiteSettings(
        title="McKeever Bros Safety",

        nav_courses="Courses",
        nav_contact="Contact us",

        hero_header="Safety training specialists",
        hero_description="McKeever Bros Safety is a leading provider in Health & Safety Courses, specialising in Manual Handling Training.",
        hero_button_label="Get in touch",

        about_column_one_header = "Local",
        about_column_one_description = "McKeever Bros Safety is a leading provider in Health & Safety Courses, specialising in Manual Handling Training. Our accredited instructors provide the highest quality training to keep your workplace safe and compliant with current regulatory requirements.",
        about_column_two_header = "Flexible",
        about_column_two_description = "Based in Ballymount, Dublin 24, we cater for both individuals and groups. Our Training Courses can be carried out at our premises or on site, at a location that suits you. Same day certification is provided on completion.",
        about_column_three_header = "Quality",
        about_column_three_description = "At McKeever Bros Safety we pride ourselves in providing the highest standard of health and safety training at competitive prices. Our courses are interactive, fun and delivered by experienced QQI certified instructors.",

        courses_header = "What we offer",
        courses_description = "McKeever Bros Safety is a leading provider in Health & Safety Courses, specialising in Manual Handling Training. Our accredited instructors provide the highest quality training to keep your workplace safe and compliant with current regulatory requirements.",

        courses_manual_handling_header = "Our Manual Handling Course",
        courses_manual_handling_description = "",

        courses_other_courses_header = "Additional courses",
        courses_other_courses_description = "We provide a number of other courses. For more information get in touch.",

        reviews_header = "Customer reviews",

        reviews_column_one_description = "\"It is not easy to find an instructor who is so engaging and informative. Learnt a lot of new things about Manual handling that will stand to me and my employees\"",
        reviews_column_one_author = "Tim Wyse",

        reviews_column_two_description = "\"Needed a manual handling and Fire Safety course for 8 of my employees and Jack worked around my schedule to get it done for me. very helpful and engaging course. Highly recommend to anyone looking to get their safety trainings up to date.\"",
        reviews_column_two_author = "Alex Gogarty",

        reviews_column_three_description = "\"The approach works very well, will be recommending Trojan Safety Training to our business associates for sure.\"",
        reviews_column_three_author = "Phil McCann",

        contact_header = "Get in touch",
        contact_description = "Help us to help you! Give us a call or send us an email with your requirements and we will be sure to help.",
        email = "info@mckeeverbrossafety.com",
        phone = "+353 87 222 1736",
    )

    with transaction.atomic():
        site_settings.save()

    ManualHandlingSummaryItem.objects.create(
        label = "1-3 Hours (Depending on number of participants)",
        icon_name = "calendar-day"
    )

    ManualHandlingSummaryItem.objects.create(
        label = "Location that suits you! We deliver training throughout Dublin & Ireland",
        icon_name = "location-arrow"
    )

    ManualHandlingSummaryItem.objects.create(
        label = "Experience Level - All Levels",
        icon_name = "chart-bar"
    )

    ManualHandlingCourseOutlineItem.objects.create(
        label = "Manual Handling Legislation",
    )

    ManualHandlingCourseOutlineItem.objects.create(
        label = "Musculoskeletal system",
    )

    ManualHandlingCourseOutlineItem.objects.create(
        label = "Ergonomics",
    )

    OtherCoursesItem.objects.create(
        label = "Fire safetey",
    )

    OtherCoursesItem.objects.create(
        label = "CPR",
    )

    OtherCoursesItem.objects.create(
        label = "Working at heights",
    )
    


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_data,
            reverse_code=migrations.RunPython.noop
        ),
    ]

