# Generated by Django 4.0.1 on 2022-04-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_sitesettings_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='courses_url',
            field=models.URLField(default='https://mckeeverbrossafety.mykademy.com/'),
        ),
    ]
