# Generated by Django 4.0.1 on 2022-04-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sitesettings_courses_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='courses_booking_prompt',
            field=models.URLField(default=''),
        ),
    ]
